language: python
python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.6
      env: NAME="cython-csg"
      install:
        - pip install cython
        - pip install -r requirements-cython-csg.txt
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install -r requirements.txt
  - pip install -r requirements-sphinx.txt
script:
  - python -m unittest discover tests
  - bash run_examples.sh
  - (cd docs ; make doctest)
