language: python
python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install -r requirements.txt
  - pip install -r requirements-cython-csg.txt
script:
  - python -m unittest discover tests
  - bash run_examples.sh
